export const flights = [
  { id: "1", name: "BC302", start: "CO", destination: "TX" },
  { id: "2", name: "BC303", start: "WY", destination: "NY" },
  { id: "3", name: "XA303", start: "HO", destination: "FL" },
  { id: "4", name: "XA304", start: "CO", destination: "TX" },
  { id: "5", name: "XA305", start: "WY", destination: "NY" },
  { id: "6", name: "XA306", start: "HO", destination: "FL" },
  { id: "7", name: "XA307", start: "CO", destination: "TX" },
  { id: "8", name: "XA308", start: "WY", destination: "NY" },
  { id: "9", name: "XA309", start: "HO", destination: "FL" },
  { id: "10", name: "XA310", start: "CO", destination: "TX" },
  { id: "11", name: "XA311", start: "WY", destination: "NY" },
  { id: "12", name: "XA312", start: "HO", destination: "FL" },
  { id: "13", name: "XA313", start: "CO", destination: "TX" },
  { id: "14", name: "XA314", start: "WY", destination: "NY" },
];

export const seats = [
  {
    id: "1",
    flightId: "1",
    row: 1,
    column: 1,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A1",
    isOccupied: false,
  },
  {
    id: "2",
    flightId: "1",
    row: 1,
    column: 2,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A2",
    isOccupied: false,
  },
  {
    id: "3",
    flightId: "1",
    row: 1,
    column: 3,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A3",
    isOccupied: false,
  },
  {
    id: "4",
    flightId: "1",
    row: 1,
    column: 4,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A4",
    isOccupied: false,
  },
  {
    id: "5",
    flightId: "1",
    row: 1,
    column: 5,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A5",
    isOccupied: false,
  },
  {
    id: "6",
    flightId: "1",
    row: 1,
    column: 6,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A6",
    isOccupied: false,
  },
  {
    id: "7",
    flightId: "1",
    row: 1,
    column: 7,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A7",
    isOccupied: false,
  },
  {
    id: "8",
    flightId: "1",
    row: 1,
    column: 8,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A8",
    isOccupied: false,
  },
  {
    id: "9",
    flightId: "1",
    row: 1,
    column: 9,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A9",
    isOccupied: false,
  },
  {
    id: "10",
    flightId: "1",
    row: 1,
    column: 10,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "A10",
    isOccupied: false,
  },
  {
    id: "11",
    flightId: "1",
    row: 2,
    column: 1,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B1",
    isOccupied: false,
  },
  {
    id: "12",
    flightId: "1",
    row: 2,
    column: 2,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B2",
    isOccupied: false,
  },
  {
    id: "13",
    flightId: "1",
    row: 2,
    column: 3,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B3",
    isOccupied: false,
  },
  {
    id: "14",
    flightId: "1",
    row: 3,
    column: 4,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B4",
    isOccupied: true,
  },
  {
    id: "15",
    flightId: "1",
    row: 3,
    column: 5,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B5",
    isOccupied: false,
  },
  {
    id: "16",
    flightId: "1",
    row: 3,
    column: 6,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B6",
    isOccupied: false,
  },
  {
    id: "17",
    flightId: "1",
    row: 3,
    column: 7,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B7",
    isOccupied: true,
  },
  {
    id: "18",
    flightId: "1",
    row: 3,
    column: 8,
    seatPrice: 100,
    seatClass: "Economy",
    seatCode: "B8",
    isOccupied: false,
  },
];
