export const flights = [
  { id: 1, name: "BC302", start: "CO", destination: "TX" },
  { id: 2, name: "BC303", start: "WY", destination: "NY" },
  { id: 3, name: "XA303", start: "HO", destination: "FL" },
  { id: 4, name: "XA304", start: "CO", destination: "TX" },
  { id: 5, name: "XA305", start: "WY", destination: "NY" },
  { id: 6, name: "XA306", start: "HO", destination: "FL" },
  { id: 7, name: "XA307", start: "CO", destination: "TX" },
  { id: 8, name: "XA308", start: "WY", destination: "NY" },
  { id: 9, name: "XA309", start: "HO", destination: "FL" },
  { id: 10, name: "XA310", start: "CO", destination: "TX" },
  { id: 11, name: "XA311", start: "WY", destination: "NY" },
  { id: 12, name: "XA312", start: "HO", destination: "FL" },
  { id: 13, name: "XA313", start: "CO", destination: "TX" },
  { id: 14, name: "XA314", start: "WY", destination: "NY" },
];

export const seats = [
  {
    id: 1,
    flightId: 1,
    seatNumber: 1,
    row: 1,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 2,
    flightId: 1,
    seatNumber: 2,
    row: 2,
    column: 2,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 3,
    flightId: 1,
    seatNumber: 3,
    row: 3,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 4,
    flightId: 2,
    seatNumber: 4,
    row: 1,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 5,
    flightId: 2,
    seatNumber: 5,
    row: 2,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 6,
    flightId: 2,
    seatNumber: 6,
    row: 3,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 7,
    flightId: 3,
    seatNumber: 7,
    row: 1,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 8,
    flightId: 3,
    seatNumber: 8,
    row: 1,
    column: 2,
    seatClass: "Economy",
    seatPrice: 100,
  },
  {
    id: 9,
    flightId: 3,
    seatNumber: 9,
    row: 2,
    column: 1,
    seatClass: "Economy",
    seatPrice: 100,
  },
];
